server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "b6ecf95f3f34d67e3d433999202e9c68496d0371141548ab07be6f66de591b1a"
  valid-duration: 600
  refreshable-durarion: 12000

